"""empty message

Revision ID: 5edb4a94c105
Revises: 
Create Date: 2018-03-25 22:46:52.422983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edb4a94c105'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='accountstatus'), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_created'), 'account', ['created'], unique=False)
    op.create_index(op.f('ix_account_updated'), 'account', ['updated'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('stocking_level', sa.Integer(), nullable=True),
    sa.Column('availability_level', sa.Integer(), nullable=True),
    sa.Column('consumable', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_consumable'), 'inventory', ['consumable'], unique=False)
    op.create_index(op.f('ix_inventory_created'), 'inventory', ['created'], unique=False)
    op.create_index(op.f('ix_inventory_updated'), 'inventory', ['updated'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('inv_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='orderstatus'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('milestones', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('shopping_list', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_created'), 'order', ['created'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_updated'), 'order', ['updated'], unique=False)
    op.create_table('stocking_location',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_warehouse', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('inventory_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('pending', 'available', 'commissioned', 'perished', name='assetstatus'), nullable=True),
    sa.Column('location_id', sa.String(length=40), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['stocking_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_created'), 'asset', ['created'], unique=False)
    op.create_index(op.f('ix_asset_status'), 'asset', ['status'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.Enum('none', 'purchase', 'fee', 'refund', 'reconciliation', 'transfer', 'misc', name='transactiontype'), nullable=True),
    sa.Column('payee', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('account_id', sa.String(length=40), nullable=True),
    sa.Column('order_id', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('agent_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_created'), 'transaction', ['created'], unique=False)
    op.create_index(op.f('ix_transaction_payee'), 'transaction', ['payee'], unique=False)
    op.create_index(op.f('ix_transaction_type'), 'transaction', ['type'], unique=False)
    op.create_table('asset_on_order',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('asset_id', sa.String(length=40), nullable=True),
    sa.Column('order_id', sa.String(length=40), nullable=True),
    sa.Column('is_replenishment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_on_order_is_replenishment'), 'asset_on_order', ['is_replenishment'], unique=False)
    op.create_table('inventory_activity',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('asset_id', sa.String(length=40), nullable=True),
    sa.Column('inventory_id', sa.String(length=40), nullable=True),
    sa.Column('activity_type', sa.Enum('create', 'decommission', 'update', name='inventoryactivitytype'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_activity_activity_type'), 'inventory_activity', ['activity_type'], unique=False)
    op.create_index(op.f('ix_inventory_activity_updated'), 'inventory_activity', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_activity_updated'), table_name='inventory_activity')
    op.drop_index(op.f('ix_inventory_activity_activity_type'), table_name='inventory_activity')
    op.drop_table('inventory_activity')
    op.drop_index(op.f('ix_asset_on_order_is_replenishment'), table_name='asset_on_order')
    op.drop_table('asset_on_order')
    op.drop_index(op.f('ix_transaction_type'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_payee'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_created'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_asset_status'), table_name='asset')
    op.drop_index(op.f('ix_asset_created'), table_name='asset')
    op.drop_table('asset')
    op.drop_table('stocking_location')
    op.drop_index(op.f('ix_order_updated'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_created'), table_name='order')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_index(op.f('ix_inventory_updated'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_created'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_consumable'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_account_updated'), table_name='account')
    op.drop_index(op.f('ix_account_created'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
